Create table fema_disaster (
 femaDeclarationString varchar(255) not null,
 disasterNumber varchar(255) not null,
 state varchar(255) not null,
 declarationType varchar(255) not null,
 declarationDate varchar(255) not null,
 fyDeclared varchar(255) not null,
 incidentType varchar(255) not null,
 declarationTitle varchar(255) not null,
 ihProgramDeclared varchar(255) not null,
 iaProgramDeclared varchar(255) not null,
 paProgramDeclared varchar(255) not null,
 hmProgramDeclared varchar(255) not null,
 incidentBeginDate varchar(255) not null,
 incidentEndDate varchar(255) not null,
 disasterCloseoutDate varchar(255) not null,
 fipsStateCode varchar(255) not null,
 fipsCountyCode varchar(255) not null,
 placeCode varchar(255) not null,
 designatedArea varchar(255) not null,
 declarationRequestNumber varchar(255) not null,
 hash varchar(255) not null primary key,
 lastRefresh varchar(255) not null,
 id varchar(255) not null
 );
